# Generated by Django 6.0.2 on 2026-02-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('buy_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cb_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('flag_url', models.URLField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
    ]
